// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterClient(arg1:any):Promise<string>;

export function SendFile(arg1:Array<string>,arg2:string,arg3:Array<number>):Promise<void>;

export function UnregisterClient(arg1:string):Promise<void>;
