// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RegisterClient(arg1) {
  return window['go']['streaming']['FileStream']['RegisterClient'](arg1);
}

export function SendFile(arg1, arg2, arg3) {
  return window['go']['streaming']['FileStream']['SendFile'](arg1, arg2, arg3);
}

export function UnregisterClient(arg1) {
  return window['go']['streaming']['FileStream']['UnregisterClient'](arg1);
}
