// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastPDF(arg1:Array<number>):Promise<void>;

export function BroadcastPage(arg1:number):Promise<void>;

export function OnPDFUpdate(arg1:any):Promise<void>;

export function OnPageUpdate(arg1:any):Promise<void>;
