// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BroadcastPDF(arg1) {
  return window['go']['streaming']['PDFStream']['BroadcastPDF'](arg1);
}

export function BroadcastPage(arg1) {
  return window['go']['streaming']['PDFStream']['BroadcastPage'](arg1);
}

export function OnPDFUpdate(arg1) {
  return window['go']['streaming']['PDFStream']['OnPDFUpdate'](arg1);
}

export function OnPageUpdate(arg1) {
  return window['go']['streaming']['PDFStream']['OnPageUpdate'](arg1);
}
