// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function Login(arg1:string,arg2:string):Promise<models.Usuario>;

export function Register(arg1:models.Usuario):Promise<models.Usuario>;
