// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Login(arg1, arg2) {
  return window['go']['server']['Auth']['Login'](arg1, arg2);
}

export function Register(arg1) {
  return window['go']['server']['Auth']['Register'](arg1);
}
